package com.mlink.base.entity;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_a
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    private String testA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_b
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    private String testB;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_a
     *
     * @return the value of test.test_a
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    public String getTestA() {
        return testA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_a
     *
     * @param testA the value for test.test_a
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    public void setTestA(String testA) {
        this.testA = testA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_b
     *
     * @return the value of test.test_b
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    public String getTestB() {
        return testB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_b
     *
     * @param testB the value for test.test_b
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    public void setTestB(String testB) {
        this.testB = testB;
    }
}