package com.mlink.base.mapper;

import com.mlink.base.entity.Test;
import java.util.List;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    int deleteByPrimaryKey(String testA);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    Test selectByPrimaryKey(String testA);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    List<Test> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Tue Jul 17 21:02:10 CST 2018
     */
    int updateByPrimaryKey(Test record);
}